using System.Text.Json;
using Overlay.Core;
using Overlay.Core.ChampionDb;
using Overlay.Core.Combo;

namespace Overlay.Core.Tests;

/// <summary>
/// Guards the first-pass, auto-generated per-skill damage maps (see
/// tools/ChampionDataGen SkillDamageGen): every generated skill_damage/*.json must be valid
/// JSON that loads through <see cref="SkillDamageDb"/> without throwing, the auto-picked
/// primary calc for a sample of non-curated champions must resolve to a POSITIVE number via
/// <see cref="SkillDamage.ComputeCalcDamage"/> (proving the pick is a real, evaluable BIN
/// calc — not a broken reference), and the 5 HAND-VERIFIED curated files must NOT be stamped
/// <c>"auto": true</c> (i.e. the generator never overwrote them).
/// </summary>
public class AllChampionSkillDataTests : IDisposable
{
    private static readonly string[] CuratedChampions = { "Aatrox", "Ahri", "Annie", "Jinx", "Zed" };
    private static readonly string[] Slots = { "Q", "W", "E", "R" };

    public AllChampionSkillDataTests()
    {
        ChampionRepository.ResetForTests();
        ChampionSummary.ResetForTests();
        SkillDamageDb.ResetForTests();
    }

    public void Dispose()
    {
        ChampionRepository.ResetForTests();
        ChampionSummary.ResetForTests();
        SkillDamageDb.ResetForTests();
    }

    private static string SkillDamageDir => Path.Combine(AppContext.BaseDirectory, "data", "skill_damage");

    private static void InitRepositoryFromCache()
    {
        var dataDir = Path.Combine(AppContext.BaseDirectory, "data");
        var ddragonRoot = Path.Combine(dataDir, "ddragon");
        var summary = Directory.GetFiles(ddragonRoot, "champion.json", SearchOption.AllDirectories)
            .OrderBy(p => p, StringComparer.Ordinal).Last();
        ChampionRepository.InitializeFromCache(
            Path.GetDirectoryName(summary)!, Path.Combine(dataDir, "communitydragon"));
    }

    // ── every generated file is valid JSON and loads through SkillDamageDb ─────────────

    [Fact]
    public void EveryGeneratedFile_IsValidJson_AndLoadsWithoutThrowing()
    {
        var files = Directory.GetFiles(SkillDamageDir, "*.json");
        Assert.True(files.Length > 100, $"expected the full generated roster, found {files.Length} files");

        foreach (var file in files)
        {
            // 1. Valid JSON.
            using (var doc = JsonDocument.Parse(File.ReadAllText(file)))
            {
                Assert.Equal(JsonValueKind.Object, doc.RootElement.ValueKind);
            }

            // 2. Loads through SkillDamageDb for every slot without throwing (the "auto" marker
            //    and "_note" must be tolerated, not choke deserialization).
            var championId = Path.GetFileNameWithoutExtension(file);
            foreach (var slot in Slots)
            {
                var ex = Record.Exception(() => SkillDamageDb.GetHits(championId, slot));
                Assert.Null(ex);
            }
        }
    }

    // ── a sample non-curated champion's auto-picked calc resolves to a positive number ─

    [Theory]
    [InlineData("Lux")]
    [InlineData("Garen")]
    [InlineData("Darius")]
    [InlineData("Yasuo")]
    [InlineData("Zeri")] // Zoe is deliberately excluded: it is a known 0-slot champion whose
                         // damage calcs the first-pass heuristic can't resolve (needs curation).
    public void SampleNonCuratedChampion_HasAtLeastOneResolvingCalc(string championId)
    {
        Assert.DoesNotContain(championId, CuratedChampions);

        InitRepositoryFromCache();
        var champion = ChampionRepository.Get(championId);
        Assert.NotNull(champion);

        var stats = new ActivePlayerStats
        {
            AttackDamage = 100,
            AbilityPower = 100,
            AbilityQ = 5,
            AbilityW = 5,
            AbilityE = 5,
            AbilityR = 3,
        };

        bool anyPositive = false;
        foreach (var slot in Slots)
        {
            var hits = SkillDamageDb.GetHits(championId, slot);
            if (hits is null) continue;
            foreach (var hit in hits)
            {
                var value = SkillDamage.ComputeCalcDamage(champion!, slot, hit.Calc, stats, level: 18);
                if (value is > 0) anyPositive = true;
            }
        }

        Assert.True(anyPositive,
            $"{championId}: no generated slot's calc resolved to a positive damage number");
    }

    // ── the 5 curated files are untouched (no "auto" marker) ──────────────────────────

    [Fact]
    public void CuratedFiles_AreNotAutoGenerated()
    {
        foreach (var champion in CuratedChampions)
        {
            var path = Path.Combine(SkillDamageDir, champion + ".json");
            Assert.True(File.Exists(path), $"curated file missing: {champion}.json");

            using var doc = JsonDocument.Parse(File.ReadAllText(path));
            Assert.False(
                doc.RootElement.TryGetProperty("auto", out _),
                $"curated file {champion}.json must NOT carry the \"auto\" marker (it would mean it was overwritten)");
        }
    }
}
